CREATE TABLE [dbo].[tblQuestionAnswer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [AnswerID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [tblAnswer]([Id]) NOT NULL, 
    [QuestionID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [tblQuestion]([Id]) NOT NULL, 
    [IsCorrect] BIT NOT NULL
)
